# Generated by Django 5.2.6 on 2026-03-18 12:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('player_x', models.CharField(blank=True, max_length=100, null=True)),
                ('player_o', models.CharField(blank=True, max_length=100, null=True)),
                ('player_x_name', models.CharField(default='Player X', max_length=100, null=True)),
                ('player_o_name', models.CharField(default='Player O', max_length=100, null=True)),
                ('board_state', models.TextField(default='["", "", "", "", "", "", "", "", ""]')),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for players'), ('active', 'Active'), ('finished', 'Game finished')], default='waiting', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
