# Generated by Django 5.2.6 on 2026-04-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='room_code',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
