# Generated by Django 5.2.6 on 2026-04-23 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('mode', models.CharField(choices=[('local', 'Local'), ('online', 'Online')], default='online', max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for players'), ('playing', 'In progress'), ('finished', 'Finished')], default='waiting', max_length=10)),
                ('current_turn', models.IntegerField(default=0)),
                ('game_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue')], max_length=10)),
                ('is_host', models.BooleanField(default=False)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='ludo.game')),
            ],
            options={
                'unique_together': {('game', 'color')},
            },
        ),
    ]
